# Generated by Django 2.0.8 on 2018-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0002_calendarevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='constant_cooperation',
            field=models.BooleanField(default=False, verbose_name='Constant Cooperation'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='ongoing',
            field=models.BooleanField(default=False, verbose_name='Ongoing Exhibition'),
        ),
    ]
